Parameters:
  Environment:
    Description: Environment
    Type: String
    Default: dev
  ECRName:
    Description: ECR name
    Type: String
    Default: newpacktdelivery
  DefaultTag:
    Description: Tag name for docker images
    Type: String
    Default: dev
  AWSAccountId:
    Description: Account Id
    Type: String
    Default: myaccountid
Resources:
  PacktDeliveryCodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AWS-NewPacktDelivery
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  PacktDeliveryCodePipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub packt-delivery-pipeline-${Environment}
  PacktDeliveryJakartaeeCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub packt-delivery-jakartaee-code-build-${Environment}
      Description: CodeBuild for Jakarta side
      ServiceRole: !GetAtt PacktDeliveryCodePipelineRole.Arn
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        PrivilegedMode: true
        EnvironmentVariables:
         - Name: IMAGE_REPO_NAME
           Value: !Sub ${ECRName}
         - Name: IMAGE_TAG
           Value: !Sub ${DefaultTag}
         - Name: AWS_ACCOUNT_ID
           Value: !Sub ${AWSAccountId}
      Source:
        Location: !Sub packt-delivery-pipeline-${Environment}/packtdelivery.zip
        Type: S3
      TimeoutInMinutes: 10
    DependsOn:
      - PacktDeliveryCodePipelineBucket
