Parameters:
  Environment:
    Description: Environment
    Type: String
    Default: dev
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub newpacktdelivery${Environment}
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
            ForwardedValues: 
              QueryString: false
            TargetOriginId: !Sub S3-newpacktdeliveryp${Environment}
            ViewerProtocolPolicy: allow-all
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Origins:
          - Id: !Sub S3-newpacktdeliveryp${Environment}
            DomainName: !Sub newpacktdelivery${Environment}.s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: ''
      Tags:
        - Key: "env"
          Value: !Sub ${Environment}